### PR TITLE
Update README to reflect usage of 1.60 rather than 1.53.

### PR DESCRIPTION
**Pull request by waywardmonkeys**

### CODE REVIEW

**Comment by sonoro1234** [comment]
Extrawurst seems temporally disconected
see #58

**Comment by sonoro1234** [comment]
v1.62.0-beta in https://github.com/sonoro1234/cimgui

**Comment by fabulousduck** [comment]
@sonoro1234 Since I can't create an issue on your fork, i guess I will do it here.

There seems to be a problem with the generator.lua file when executed ons OSX with lua 5.3.

```bash
**$ lua generator.lua
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin

HAVE_GCC	true
lua: generator.lua:259: invalid use of '%' in replacement string
stack traceback:
	[C]: in function 'string.gsub'
	generator.lua:259: in field 'insert'
	generator.lua:909: in main chunk
	[C]: in ?**
```

I don't know if this is an issue on my side or on the side of the script, but any help with getting this build to work would be highly appriciated.

**Comment by fabulousduck** [comment]
It does seem to work with luaJIT.

**Comment by sonoro1234** [comment]
Yes
https://github.com/sonoro1234/cimgui/blob/Branch_v1.62.0/generator/generator.lua#L3

**Pull request closed without merging**
